### PR TITLE
feat: remove vtk dependency to calculate tetrahedron volume

### PR DESCRIPTION
**Pull request by madsendennis**
Remove vtk dependency to calculate tetrahedron volume. 
Part of the steps to move away from VTK, https://github.com/unibas-gravis/scalismo/issues/415

### CODE REVIEW

**Comment by Andreas-Forster** [comment]
I would vote for moving it to another location. @marcelluethi what do you think? Maybe `scalismo.numerics` would also be an option?

**Comment by madsendennis** [comment]
> I would vote for moving it to another location. @marcelluethi what do you think? Maybe `scalismo.numerics` would also be an option?

Good idea. I think `scalismo.numerics` makes sense as well. I've pushed an update. Then hopefully it is directly ready to merge when Marcel gets time to look over it.

**Review by Andreas-Forster — APPROVED** [review]
Thank you for this PR.

**Review by marcelluethi — APPROVED** [review]
This looks good to me.

**Pull request merged**
