### PR TITLE
Tetrahedral

### PR DESCRIPTION
**Pull request by rassaire**
WIP:

1. 

The implementation of the tetrahedral features  that include:

- Reading a tetrahedral mesh (unstructured grid) (.inp .vtu,.vtk)
- defining and transforming the tetrahedral mesh structure similarly to triangle Mesh 
- writing a tetrahedral Mesh (.vtu, .vtk)

2.

The implementation of the intensity representation from row image through the tetrahedral mesh:
- Use Bernstein polynomial interpolation ( each tetrahedron of the tetrahedral Mesh being reprentaed by density function )

### CODE REVIEW

**Comment by marcelluethi** [comment]
Thanks a lot for this PR. I added @Andreas-Forster @DanaRahbani @kahrpatrick @madsendennis  as reviewers, to invite them to participate in a discussion and collaboration.

**Comment by rassaire** [comment]
You are welcome, yes I forgot to add them.


Jean-Rassaire

*AIMS alumnus | MSc **Biomedical Eng* *|* *PhD candidate (**Biomedical Eng)*
*University of Cape Town, South Africa | **IMT Atlantique, Brest, France*

*fjrassaire@gmail.co <fjrassaire@gmail.com>m;  ffcjea001@myuct.ac.za
<ffcjea001@myuct.ac.za>;*
* jean-rassaire.fouefack@imt-atlantique.fr
<jean-rassaire.fouefack@imt-atlantique.fr>*
*+33 (0)774138689*
S*kype ID: rassaire.fouefack*
Twitter: @JFouefack
Linkedin:www.linkedin.com/in/jean-rassaire

Medical Image Inferencing & Distributed Diagnostics
<https://twitter.com/hashtag/MI2D2?src=hash>

Laboratory of Medical Information Processing <http://latim.univ-brest.fr/>

**Comment by marcelluethi** [comment]
I just added a tetrahedral mesh to  ```src/test/resources```. It can be used for testing. 

My initial test showed that reading and writing this mesh succeeds, but visualizing it in Paraview reveals that some faces of the tetrahedral mesh get lost.

**Comment by rassaire** [comment]
> I just added a tetrahedral mesh to `src/test/resources`. It can be used for testing.
> 
> My initial test showed that reading and writing this mesh succeeds, but visualizing it in Paraview reveals that some faces of the tetrahedral mesh get lost.

So the number of faces is less than the one from the original?

**Comment by rassaire** [comment]
> > I just added a tetrahedral mesh to `src/test/resources`. It can be used for testing.
> > My initial test showed that reading and writing this mesh succeeds, but visualizing it in Paraview reveals that some faces of the tetrahedral mesh get lost.
> 
> So the number of faces is less than the one from the original?

I have just read, written and checked in Paraview. They have the same number of faces. Find attached the picture.
Capture

**Comment by marcelluethi** [comment]
Did you check it with the mesh that I provided? The visualization in Paraview (after reading and writing) clearly shows some artifacts.

**Comment by rassaire** [comment]
> Did you check it with the mesh that I provided? The visualization in Paraview (after reading and writing) clearly shows some artifacts.

Yes, I have seen that. I am going through the code to figure out.

**Comment by marcelluethi** [comment]
I just created the following Test-code, which should illustrate how the new meshes class can be used:
```scala
object TetraTest {
  
  scalismo.initialize()
  implicit val rng = scalismo.utils.Random(42L)

  def main(args: Array[String]): Unit = {
    val referenceMesh: TetrahedralMesh[_3D] = MeshIO.readTetrahedralMesh(new java.io.File("./src/test/resources/TetraMesh.vtk")).get

    // Creating a GP
    val gk = DiagonalKernel[_3D](GaussianKernel(10), 3)
    val gp = GaussianProcess[_3D, EuclideanVector[_3D]](gk)
    val lowRankGP = LowRankGaussianProcess.approximateGPCholesky(referenceMesh.pointSet, gp, 1e-5, NearestNeighborInterpolator())

    // Creating a statistical volume model
    val volumeModel = StatisticalVolumeMeshModel(referenceMesh, lowRankGP)

    // Sampling from the models
    for (i <- 0 until 10) {
      val sampleVolume = volumeModel.sample()
      MeshIO.writeTetrahedralMesh(sampleVolume, new java.io.File(s"sample-$i.vtk")).get
    }

    // Creating scalar representations
    val scalars = referenceMesh.pointSet.points.map((pt: Point[_3D]) => 1.0).toIndexedSeq
    val volumeMeshField = ScalarVolumeMeshField(referenceMesh, scalars)
    val volumeField = volumeMeshField.interpolate(NearestNeighborInterpolator())

    // Warping a scalar volume mesh with the output of a GP
    val sampleDeformation = lowRankGP.sample()
    val warpedVolumeMeshField = volumeMeshField.transform(p => p + sampleDeformation(p))

    // val ui = ScalismoUI()
    // ui.show(volumeMeshField, "volumeMesh")
  }

}
```

@Andreas-Forster Do you agree with how this looks from the user's perspective? If yes, we can take this as a starting point for working on the visualization / registration

**Comment by madsendennis** [comment]
The `ScalarVolumeMeshField` class should be a `case class` as in ScalarMeshField to make the `.mesh` accessible.

**Comment by marcelluethi** [comment]
I agree. This should be changed when the core data structures are stabilized.

**Comment by marcelluethi** [comment]
I am closing this PR, as the core concepts from tetrahedral meshes have been integrated as separate PRs. The same will be done for the intensity models in a separate milestone

**Pull request closed without merging**
