### PR TITLE
Feat/native mesh decimation

### PR DESCRIPTION
**Pull request by madsendennis**
This is a pure scala implementation of a mesh decimation algorithm based on the Fast Quadric Mesh Simplication algorithm: https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/tree/master 

This is the first part of removing the VTK dependency in Scalismo, https://github.com/unibas-gravis/scalismo/issues/415

### CODE REVIEW

**Comment by madsendennis** [comment]
The current version is a direct conversion of the original c++ version to a scala version, so a lot of code structure still needs to be properly updated. 
For now the algorithm works, so I would love some feedback on having this algorithm in comparison to the quadratic edge collapse, which might look more appealing. 
On a side note, this algorithm is with the current implementation already ~2 times faster (on the face mesh) than the VTK decimation we currently use. 

One minor bug is that some triangle norms are inverted.

**Comment by Andreas-Forster** [comment]
I am fine with the replacement, if the normal inversion can be fixed. The old decimate could be offered as alternative in scalismo-vtk later on.

**Review by Andreas-Forster — CHANGES_REQUESTED** [review]
I fine with the replacement except for the bug you mentioned.

- [x] Fix normal bug

**Review by Andreas-Forster — APPROVED** [review]

**Review by marcelluethi — APPROVED** [review]
I think the code can be merged. I would appreciate though, if you could run sbt scalafmtAll before merging, such that we have a consistent formatting in all of Scalismo.

**Comment by madsendennis** [comment]
@Andreas-Forster is working on restructuring the code, I'll merge it in when we have a cleaner version.

**Pull request merged**
